name: deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: set up ssh
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 ${{ secrets.TARGET_SERVER_IP }} >> ~/.ssh/known_hosts
    - name: Deploy to server
      run: |
        ssh -v -o StrictHostKeyChecking=accept-new admin@${{ secrets.TARGET_SERVER_IP }} << 'ENDSSH'
        git clone https://github.com/mana-byte/quick-writing-test
        cd devweb
        docker rm -f frontend || true
        docker rm -f web || true
        docker rm -f db || true
        docker compose up -d
        ENDSSH
